i386-pc-linux: simple
i386-pc-linux-debug: debug
i386-pc-freebsd: simple
hppa1.1-hp-hpux10.20: simple
alpha-dec-osf5.1: simple
linux: simple
freebsd: simple
tuxbox: cross-powerpc-tuxbox-linux
tripledragon: cross-powerpc-405-linux
win: cross-i386-pc-cygwin
cygwin: i386-pc-cygwin
macosx: macosx-native
linux-pcsc: i386-pc-linux-pcsc
dm500: cross-powerpc-tuxbox-linux
sh4: cross-sh4-linux
sh4-stapi: cross-sh4-linux-stapi
sh4-stapi5: cross-sh4-linux-stapi5
i386-pc-linux-libusb: libusb
i386-pc-linux-pcsc: pcsc
i386-pc-linux-pcsc-libusb: pcsc-libusb
libusb-pcsc: pcsc-libusb

libusb:
	$(MAKE) --no-print-directory \
		USE_LIBUSB=1 \
		$(MAKEFLAGS)

pcsc:
	$(MAKE) --no-print-directory \
		USE_PCSC=1 \
		$(MAKEFLAGS)

pcsc-libusb:
	$(MAKE) --no-print-directory \
		USE_LIBUSB=1 \
		USE_PCSC=1 \
		$(MAKEFLAGS)

macosx-native:
	$(MAKE) --no-print-directory \
		USE_PCSC=1 \
		$(MAKEFLAGS)

macosx-libusb:
	$(MAKE) --no-print-directory \
		USE_LIBUSB=1 \
		USE_PCSC=1 \
		$(MAKEFLAGS)

cross-i386-pc-freebsd:
	$(MAKE) --no-print-directory \
		CROSS=i386-pc-freebsd5.4- \
		EXTRA_FLAGS="-static-libgcc" \
		$(MAKEFLAGS)

cross-powerpc-tuxbox-linux-uclibc:
	$(MAKE) --no-print-directory \
		CROSS=powerpc-tuxbox-linux-uclibc- \
		CONF_DIR=/var/tuxbox/config \
		$(MAKEFLAGS)

cross-powerpc-405-linux:
	$(MAKE) --no-print-directory \
		CROSS=powerpc-405-linux-gnu- \
		CONF_DIR=/var/tuxbox/config \
		EXTRA_FLAGS="-DSTB04SCI=1"
		$(MAKEFLAGS)

cross-sh4-linux:
	$(MAKE) --no-print-directory \
		CROSS=sh4-linux- \
		CONF_DIR=/var/tuxbox/config \
		$(MAKEFLAGS)

cross-sh4-linux-stapi:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		CONF_DIR=/var/tuxbox/config \
		USE_STAPI=1 \
		USE_LIBCRYPTO=1 \
		$(MAKEFLAGS)

cross-sh4-linux-stapi5:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		CONF_DIR=/var/tuxbox/config \
		USE_STAPI5=1 \
		USE_LIBCRYPTO=1 \
		USE_UTF8=1 \
		STAPI5_LIB=stapi/liboscam_stapi5_OPENBOX.a \
		$(MAKEFLAGS)

cross-i386-pc-cygwin:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		EXTRA_FLAGS="-D_WIN32 -I /tmp/include -static" \
		$(MAKEFLAGS)

cross-i386-pc-cygwin-pcsc:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		USE_PCSC=1 \
		PCSC_LIB="-lwinscard" \
		EXTRA_FLAGS="-D_WIN32 -I /tmp/include -I ./cygwin -I/usr/include/w32api -static" \
		EXTRA_LDFLAGS="" \
		$(MAKEFLAGS)

i686-pc-cygwin:
	$(MAKE) --no-print-directory \
		CROSS=i686-pc-cygwin- \
		EXTRA_FLAGS="-D_WIN32 -I /tmp/include -static" \
		$(MAKEFLAGS)

i686-pc-cygwin-pcsc:
	$(MAKE) --no-print-directory \
		CROSS=i686-pc-cygwin- \
		USE_PCSC=1 \
		PCSC_LIB="-lwinscard" \
		EXTRA_FLAGS="-D_WIN32 -I /tmp/include -I ./cygwin -I/usr/include/w32api -static" \
		EXTRA_LDFLAGS="" \
		$(MAKEFLAGS)

i686-pc-cygwin-libusb:
	$(MAKE) --no-print-directory \
		CROSS=i686-pc-cygwin- \
		USE_LIBUSB=1 \
		LIBUSB_LIB="/usr/lib/libusb-1.0.a" \
		USE_PCSC=1 \
		PCSC_LIB="-lwinscard" \
		EXTRA_LIBS="-lSetupAPI -lOle32 -lshell32" \
		EXTRA_FLAGS="-D_WIN32 -I /tmp/include -I ./cygwin -I/usr/include/w32api -static" \
		EXTRA_LDFLAGS="" \
		$(MAKEFLAGS)

x86_64-pc-cygwin:
	$(MAKE) --no-print-directory \
		EXTRA_FLAGS="-D_WIN64 -I /tmp/include -static" \
		$(MAKEFLAGS)

x86_64-pc-cygwin-pcsc:
	$(MAKE) --no-print-directory \
		USE_PCSC=1 \
		PCSC_LIB="-lwinscard" \
		EXTRA_FLAGS="-D_WIN64 -I /tmp/include -I ./cygwin -I/usr/include/w32api -static" \
		EXTRA_LDFLAGS="-L/cygdrive/c/WINDOWS/system32" \
		$(MAKEFLAGS)

cross-sparc-sun-solaris2.7:
	$(MAKE) --no-print-directory \
		CROSS=sparc-sun-solaris2.7- \
		EXTRA_LIBS="-lsocket" \
		EXTRA_FLAGS="-static-libgcc" \
		$(MAKEFLAGS)

opensolaris:
	$(MAKE) --no-print-directory \
		EXTRA_LIBS="-lsocket -lnsl" \
		EXTRA_FLAGS="-static-libgcc" \
		$(MAKEFLAGS)

cross-rs6000-ibm-aix4.2:
	$(MAKE) --no-print-directory \
		CROSS=rs6000-ibm-aix4.2- \
		LIB_PTHREAD=-lpthreads \
		EXTRA_FLAGS="-static-libgcc" \
		$(MAKEFLAGS)

cross-mips-sgi-irix6.5:
	$(MAKE) --no-print-directory \
		CROSS=mips-sgi-irix6.5- \
		EXTRA_FLAGS="-static-libgcc" \
		$(MAKEFLAGS)

cross-mipsel-routerwrtbrcm47xx-linux-uclibc:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		LIB_RT= \
		LIB_PTHREAD=$(LIB_PTHREAD) \
		EXTRA_FLAGS="-static-libgcc -I. -s" \
		EXTRA_LDFLAGS="-static" \
		CONF_DIR=/usr/local/etc \
		$(MAKEFLAGS)

cross-mips-routerwrtbrcm47xx-linux-uclibc-libusb:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		LIB_RT= \
		LIB_PTHREAD=$(LIB_PTHREAD) \
		EXTRA_FLAGS="-static-libgcc -I. -s" \
		USE_LIBUSB=1 \
		LIBUSB_LIB=$(LIBUSB_LIB) \
		EXTRA_LDFLAGS="-static" \
		CONF_DIR=/usr/local/etc \
		$(MAKEFLAGS)

cross-mips-routerwrtbrcm63xx-linux-uclibc:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		LIB_RT= \
		LIB_PTHREAD=$(LIB_PTHREAD) \
		EXTRA_FLAGS="-static-libgcc -I. -s" \
		EXTRA_LDFLAGS="-static" \
		CONF_DIR=/usr/local/etc \
		$(MAKEFLAGS)

cross-mips-routerwrtbrcm63xx-linux-uclibc-libusb:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		LIB_RT= \
		LIB_PTHREAD=$(LIB_PTHREAD) \
		EXTRA_FLAGS="-static-libgcc -I. -s" \
		USE_LIBUSB=1 \
		LIBUSB_LIB=$(LIBUSB_LIB) \
		EXTRA_LDFLAGS="-static" \
		CONF_DIR=/usr/local/etc \
		$(MAKEFLAGS)

cross-mips-routerwrtar71xx-linux-uclibc:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		LIB_RT= \
		LIB_PTHREAD=$(LIB_PTHREAD) \
		EXTRA_FLAGS="-static-libgcc -I. -s" \
		EXTRA_LDFLAGS="-static" \
		CONF_DIR=/usr/local/etc \
		$(MAKEFLAGS)

cross-mips-routerwrtar71xx-linux-uclibc-libusb:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		LIB_RT= \
		LIB_PTHREAD=$(LIB_PTHREAD) \
		EXTRA_FLAGS="-static-libgcc -I. -s" \
		USE_LIBUSB=1 \
		LIBUSB_LIB=$(LIBUSB_LIB) \
		EXTRA_LDFLAGS="-static" \
		CONF_DIR=/usr/local/etc \
		$(MAKEFLAGS)

cross-mipsel-router-linux-uclibc-libusb:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		LIB_RT= \
		LIB_PTHREAD=$(LIB_PTHREAD) \
		EXTRA_FLAGS="-static-libgcc -I. -s" \
		USE_LIBUSB=1 \
		LIBUSB_LIB=$(LIBUSB_LIB) \
		EXTRA_LDFLAGS="-static" \
		CONF_DIR=/usr/local/etc \
		$(MAKEFLAGS)

cross-mipsel-router-linux-uclibc:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		LIB_RT= \
		LIB_PTHREAD=$(LIB_PTHREAD) \
		EXTRA_FLAGS="-static-libgcc -I. -s" \
		CONF_DIR=/usr/local/etc \
		$(MAKEFLAGS)

cross-mipsel-router-linux-uclibc927: cross-mipsel-router-linux-uclibc
cross-mipsel-router-linux-uclibc928: cross-mipsel-router-linux-uclibc
cross-mipsel-router-linux-uclibc929: cross-mipsel-router-linux-uclibc

cross-mipsel-router-linux-uclibc929-static:
	$(MAKE) --no-print-directory \
		CROSS=mipsel-linux-uclibc- \
		EXTRA_FLAGS="-static-libgcc" \
		EXTRA_LDFLAGS="-static" \
		$(MAKEFLAGS)

cross-mips-router-linux-uclibc:
	$(MAKE) --no-print-directory \
		CROSS=mips-linux-uclibc- \
		EXTRA_FLAGS="-static-libgcc" \
		$(MAKEFLAGS)

cross-mips-router-linux-uclibc930: cross-mips-router-linux-uclibc
cross-mips-router-linux-uclibc931: cross-mips-router-linux-uclibc930
cross-mipsel-fonera2: cross-mips-router-linux-uclibc

cross-mipsel-tuxbox-linux-gnu-libusb-pcsc:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		CONF_DIR=/var/tuxbox/config \
		USE_PCSC=1 \
		PCSC_LIB=$(PCSC_LIB) \
		EXTRA_FLAGS="-mips1 -static-libgcc -EL -I. -s" \
		USE_LIBUSB=1 \
		LIBUSB_LIB=$(LIBUSB_LIB) \
		$(MAKEFLAGS)

cross-mipsel-tuxbox-linux-gnu:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		CONF_DIR=/var/tuxbox/config \
		EXTRA_FLAGS="-mips1 -static-libgcc -EL -I. -s" \
		$(MAKEFLAGS)

cross-mipsel-tuxbox-linux:
	$(MAKE) --no-print-directory \
		CROSS=mipsel-unknown-linux-gnu- \
		CONF_DIR=/var/tuxbox/config \
		EXTRA_FLAGS="-mips1 -static-libgcc -EL -I. -s" \
		$(MAKEFLAGS)

cross-mipsel-linux-uclibc-libusb-pcsc:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		CONF_DIR=/var/tuxbox/config \
		USE_PCSC=1 \
		PCSC_LIB=$(PCSC_LIB) \
		EXTRA_FLAGS="-mips1 -static-libgcc -EL -I. -s" \
		USE_LIBUSB=1 \
		LIBUSB_LIB=$(LIBUSB_LIB) \
		$(MAKEFLAGS)

cross-mipsel-linux-uclibc:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		CONF_DIR=/var/tuxbox/config \
		EXTRA_FLAGS="-mips1 -static-libgcc -EL -I. -s" \
		$(MAKEFLAGS)

cross-mipsel-tuxbox-linux-glibc:
	$(MAKE) --no-print-directory \
		CROSS=mipsel-linux-glibc- \
		CONF_DIR=/var/tuxbox/config \
		EXTRA_FLAGS="-mips1 -static-libgcc -EL -I. -s" \
		$(MAKEFLAGS)

cross-arm-coreelec-linux:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		CONF_DIR=/var/tuxbox/config \
		EXTRA_FLAGS="-march=armv8-a+crc -mtune=cortex-a53 -mabi=aapcs-linux -Wno-psabi -Wa,-mno-warn-deprecated -mcpu=cortex-a53 -mfloat-abi=hard -mfpu=neon-fp-armv8 -fomit-frame-pointer -Wall -pipe -Os -Wall -O2 -Os -DNDEBUG -W -Wall" \
		$(MAKEFLAGS)

cross-arm-tuxbox-linux-libusb:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		CONF_DIR=/var/tuxbox/config \
		EXTRA_FLAGS="-mtune=cortex-a9 -mcpu=cortex-a9 -mfpu=neon-vfpv4 -static-libgcc -I. -s" \
		USE_LIBUSB=1 \
		LIBUSB_LIB=$(LIBUSB_LIB) \
		$(MAKEFLAGS)

cross-arm-tuxbox-linux:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		CONF_DIR=/var/tuxbox/config \
		EXTRA_FLAGS="-mtune=cortex-a9 -mcpu=cortex-a9 -mfpu=neon-vfpv4 -static-libgcc -I. -s" \
		$(MAKEFLAGS)

cross-aarch64-tuxbox-linux-libusb:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		CONF_DIR=/var/tuxbox/config \
		EXTRA_FLAGS="-static-libgcc" \
		LIBUSB_LIB=$(LIBUSB_LIB) \
		$(MAKEFLAGS)

cross-aarch64-tuxbox-linux:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		CONF_DIR=/var/tuxbox/config \
		EXTRA_FLAGS="-static-libgcc" \
		$(MAKEFLAGS)

cross-arm-raspbian-linux-libusb:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		CONF_DIR=/var/tuxbox/config \
		EXTRA_FLAGS="-static-libgcc -I. -s" \
		USE_LIBUSB=1 \
		LIBUSB_LIB=$(LIBUSB_LIB) \
		$(MAKEFLAGS)

cross-arm-raspbian-linux:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		CONF_DIR=/var/tuxbox/config \
		EXTRA_FLAGS="-static-libgcc -I. -s" \
		$(MAKEFLAGS)

cross-arm-marvell-linux-libusb:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		CONF_DIR=/var/tuxbox/config \
		EXTRA_FLAGS="-static-libgcc -I. -s" \
		USE_LIBUSB=1 \
		LIBUSB_LIB=$(LIBUSB_LIB) \
		$(MAKEFLAGS)

cross-arm-marvell-linux:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		CONF_DIR=/usr/local/etc \
		EXTRA_LIBS="-lrt" \
		$(MAKEFLAGS)

cross-sh4-tuxbox-linux-libusb-pcsc:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		CONF_DIR=/var/tuxbox/config \
		USE_PCSC=1 \
		PCSC_LIB=$(PCSC_LIB) \
		EXTRA_FLAGS="-static-libgcc -I. -s" \
		USE_LIBUSB=1 \
		LIBUSB_LIB=$(LIBUSB_LIB) \
		$(MAKEFLAGS)

cross-sh4-tuxbox-linux:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		CONF_DIR=/var/tuxbox/config \
		EXTRA_FLAGS="-static-libgcc -I. -s" \
		$(MAKEFLAGS)

cross-x86_64-tuxbox-linux-libusb-pcsc:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		CONF_DIR=/var/tuxbox/config \
		USE_PCSC=1 \
		PCSC_LIB=$(PCSC_LIB) \
		EXTRA_FLAGS="-m64 -I. -s" \
		USE_LIBUSB=1 \
		LIBUSB_LIB=$(LIBUSB_LIB) \
		$(MAKEFLAGS)

cross-x86_64-tuxbox-linux:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		CONF_DIR=/var/tuxbox/config \
		EXTRA_FLAGS="-m64 -I. -s" \
		$(MAKEFLAGS)

cross-x86_64-tuxbox-linux-ssl:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		USE_SSL=1 \
		SSL_LIB=/usr/lib/x86_64-linux-gnu/libssl.a \
		LIBCRYPTO_LIB=/usr/lib/x86_64-linux-gnu/libcrypto.a \
		CONF_DIR=/var/tuxbox/config \
		EXTRA_FLAGS="-m64 -I. -s" \
		EXTRA_TARGET=-static \
		$(MAKEFLAGS)

cross-x86-tuxbox-linux-libusb-pcsc:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		CONF_DIR=/var/tuxbox/config \
		USE_PCSC=1 \
		PCSC_LIB=$(PCSC_LIB) \
		EXTRA_FLAGS="-m32 -I. -s" \
		USE_LIBUSB=1 \
		LIBUSB_LIB=$(LIBUSB_LIB) \
		$(MAKEFLAGS)

cross-x86-tuxbox-linux:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		CONF_DIR=/var/tuxbox/config \
		EXTRA_FLAGS="-m32 -I. -s" \
		$(MAKEFLAGS)

cross-powerpc-tuxbox-linux-libusb:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		LIB_RT=$(LIB_RT) \
		LIB_PTHREAD=$(LIB_PTHREAD) \
		CONF_DIR=/var/tuxbox/config \
		EXTRA_FLAGS="-static-libgcc -I. -s" \
		USE_LIBUSB=1 \
		LIBUSB_LIB=$(LIBUSB_LIB) \
		$(MAKEFLAGS)

cross-powerpc-tuxbox-linux:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		LIB_RT=$(LIB_RT) \
		LIB_PTHREAD=$(LIB_PTHREAD) \
		CONF_DIR=/var/tuxbox/config \
		EXTRA_FLAGS="-static-libgcc -I. -s" \
		$(MAKEFLAGS)

cross-powerpc-tuxbox-linux-exp:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		LIB_RT=$(LIB_RT) \
		LIB_PTHREAD=$(LIB_PTHREAD) \
		CONF_DIR=/var/tuxbox/config \
		EXTRA_FLAGS="-static-libgcc -I. -s" \
		$(MAKEFLAGS)

cross-ppc-tuxbox-linux:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		LIB_RT=$(LIB_RT) \
		LIB_PTHREAD=$(LIB_PTHREAD) \
		CONF_DIR=/var/tuxbox/config \
		EXTRA_FLAGS="-static-libgcc -I. -s" \
		$(MAKEFLAGS)

cross-ppc-tuxbox-linux-libusb:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		LIB_RT=$(LIB_RT) \
		LIB_PTHREAD=$(LIB_PTHREAD) \
		CONF_DIR=/var/tuxbox/config \
		EXTRA_FLAGS="-static-libgcc -I. -s" \
		USE_LIBUSB=1 \
		LIBUSB_LIB=$(LIBUSB_LIB) \
		$(MAKEFLAGS)

cross-arm-nslu2-linux:
	$(MAKE) --no-print-directory \
		CROSS=armv5b-softfloat-linux- \
		$(MAKEFLAGS)

cross-armBE-unknown-linux:
	$(MAKE) --no-print-directory \
		CROSS=arm-linux- \
		EXTRA_FLAGS="-mbig-endian" \
		$(MAKEFLAGS)

cross-armBE-unkown-linux: cross-armBE-unknown-linux

cross-armLE-unknown-linux:
	$(MAKE) --no-print-directory \
		CROSS=arm-linux- \
		EXTRA_FLAGS="-mlittle-endian" \
		$(MAKEFLAGS)

cross-armLE-unkown-linux: cross-armLE-unknown-linux

gx:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		CONF_DIR=/home/gx/ncam \
		USE_GXAPI=1 \
		EXTRA_FLAGS="-I ./extapi/goceed" \
		$(MAKEFLAGS)

azbox:
	$(MAKE) --no-print-directory \
		CROSS=mipsel-linux-uclibc- \
		CONF_DIR=/PLUGINS/OpenXCAS/ncamCAS \
		USE_AZBOX=1 \
		$(MAKEFLAGS)

mca:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		CONF_DIR=/var/mca/d1 \
		USE_MCA=1 \
		$(MAKEFLAGS)

cool:
	$(MAKE) --no-print-directory \
		CROSS=arm-cx2450x-linux-gnueabi- \
		CONF_DIR=/var/tuxbox/config \
		USE_COOLAPI=1 \
		$(MAKEFLAGS)

cool2:
	$(MAKE) --no-print-directory \
		CROSS=arm-pnx8400-linux-uclibcgnueabi- \
		CONF_DIR=/var/tuxbox/config \
		USE_COOLAPI2=1 \
		$(MAKEFLAGS)

neutrinohd: cool
coolstream: cool

neutrinohd2: cool2
coolstream2: cool2

su980:
	$(MAKE) --no-print-directory \
		CROSS=arm-cortex-linux-gnueabi- \
		CONF_DIR=/var/tuxbox/config \
		USE_SU980=1 \
		$(MAKEFLAGS)

hypercube: su980

dockstar:
	$(MAKE) --no-print-directory \
		CROSS=arm-openwrt-linux-uclibcgnueabi- \
		CONF_DIR=/jffs/etc/config/ncam \
		$(MAKEFLAGS)

qboxhd:
	$(MAKE) --no-print-directory \
		CROSS=sh4-linux- \
		EXTRA_FLAGS="-DQBOXHD=1" \
		PLUS_TARGET=-qboxhd \
		CONF_DIR=/var/tuxbox/config \
		$(MAKEFLAGS)

static:
	$(MAKE) --no-print-directory \
		EXTRA_FLAGS=-static \
		EXTRA_TARGET=-static \
		$(MAKEFLAGS)

static-libusb:
	$(MAKE) --no-print-directory \
		USE_LIBUSB=1 \
		LIBUSB_LIB=/usr/lib/libusb-1.0.a \
		EXTRA_TARGET=-static \
		$(MAKEFLAGS)

static-libcrypto:
	$(MAKE) --no-print-directory \
		USE_LIBCRYPTO=1 \
		LIBCRYPTO_LIB=/usr/lib/libcrypto.a \
		EXTRA_TARGET=-static \
		$(MAKEFLAGS)

static-ssl:
	$(MAKE) --no-print-directory \
		USE_SSL=1 \
		SSL_LIB=/usr/lib/libssl.a \
		LIBCRYPTO_LIB=/usr/lib/libcrypto.a \
		EXTRA_TARGET=-static \
		$(MAKEFLAGS)

android-arm:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		LIB_RT= \
		LIB_PTHREAD= \
		ANDROID_NDK=1 \
		USE_SSL=1 \
		SSL_LIB=$(SSL_LIB) \
		LIBCRYPTO_LIB=$(LIBCRYPTO_LIB) \
		EXTRA_FLAGS="-pie -I. -s" \
		$(MAKEFLAGS)

android-arm-libusb:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		LIB_RT= \
		LIB_PTHREAD= \
		ANDROID_NDK=1 \
		USE_SSL=1 \
		SSL_LIB=$(SSL_LIB) \
		LIBCRYPTO_LIB=$(LIBCRYPTO_LIB) \
		EXTRA_FLAGS="-pie -I. -s" \
		USE_LIBUSB=1 \
		LIBUSB_LIB=$(LIBUSB_LIB) \
		$(MAKEFLAGS)

android-arm-stapi:
	$(MAKE) --no-print-directory \
		CROSS=$(CROSS) \
		LIB_RT= \
		LIB_PTHREAD= \
		USE_LIBCRYPTO=1 \
		CONF_DIR=/data/plugin/ncam \
		USE_WI=1 \
		$(MAKEFLAGS)

android-ndk: ndk
	$(MAKE) --no-print-directory \
		CC="$(NDK_ROOT)/toolchains/llvm/prebuilt/linux-x86_64/bin/$(target)-clang $(flags)" \
		STRIP=$(NDK_ROOT)/toolchains/llvm/prebuilt/linux-x86_64/bin/$(host)-strip \
		LIB_RT= \
		LIB_PTHREAD= \
		EXTRA_FLAGS="$(EXTRA_FLAGS)" \
		EXTRA_LDFLAGS="$(EXTRA_LDFLAGS) $(ldflags)" \
		$(MAKEFLAGS)

ndk:
ifdef ANDROID_NDK
NDK_ROOT = $(ANDROID_NDK)
endif
ifndef ARCH
ARCH = arm
endif
ifndef API
API = 16
endif
flags = $(FLAGS) -fpic -fno-addrsig -ffunction-sections -fdata-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -DANDROID -D__ANDROID_API__=$(API)
ifeq ($(ARCH),arm)
host = arm-linux-androideabi
target = armv7a-linux-androideabi$(API)
ifdef USE_WI
flags += -march=armv7-a -mcpu=cortex-a8 -mfloat-abi=softfp -mfpu=neon
ldflags = -march=armv7-a -Wl,--fix-cortex-a8
else
flags += -march=armv7-a -mtune=cortex-a9 -mfloat-abi=softfp -mfpu=vfpv3-d16
endif
else ifeq ($(ARCH),x86)
host = i686-linux-android
target = $(host)$(API)
else ifeq ($(ARCH),arm64)
host = aarch64-linux-android
target = $(host)$(API)
else ifeq ($(ARCH),x86_64)
host = x86_64-linux-android
target = $(host)$(API)
endif

uclinux:
	$(MAKE) --no-print-directory \
		LIB_DL= STRIP=true \
		CROSS=m68k-uclinux- \
		$(MAKEFLAGS)
