.TH list_smargo 1
.SH NAME
\fBlist_smargo\fR - list all connected Smartreader+
.SH SYNOPSIS
list_smargo
.SH DESCRIPTIONS
The list_smargo software lists all connected Smartreader+ with bus number and device address.
.RE
.SH "SEE ALSO"
\fBncam\fR(1), \fBncam.ac\fR(5), \fBncam.cacheex\fR(5), \fBncam.cert\fR(5),  \fBncam.conf\fR(5), \fBncam.dvbapi\fR(5), \fBncam.fakecws\fR(5), \fBncam.guess\fR(5), \fBncam.ird\fR(5), \fBncam.provid\fR(5), \fBncam.ratelimit\fR(5), \fBncam.server\fR(5), \fBncam.services\fR(5), \fBncam.srvid\fR(5), \fBncam.srvid2\fR(5), \fBncam.tiers\fR(5), \fBncam.user\fR(5), \fBncam.whitelist\fR(5)
