.TH ncam.ird 5
.SH NAME
\fBncam.ird\fR - Irdeto guessing table for NCAm
.SH SYNOPSIS
Irdeto guessing table
.SH DESCRIPTIONS
.PP
\fB<byte3>\fP:\fB<byte4-7>\fP:\fB<CAID>\fP:\fB<SID>\fP
.RS 3n
Irdeto guessing table by signature
.RE
.SH EXAMPLES
 12:0000000a:12ab:cd01
.SH "SEE ALSO"
\fBlist_smargo\fR(1), \fBncam\fR(1), \fBncam.ac\fR(5), \fBncam.cacheex\fR(5), \fBncam.cert\fR(5), \fBncam.conf\fR(5), \fBncam.dvbapi\fR(5), \fBncam.fakecws\fR(5), \fBncam.guess\fR(5), \fBncam.provid\fR(5), \fBncam.ratelimit\fR(5), \fBncam.server\fR(5), \fBncam.services\fR(5), \fBncam.srvid\fR(5), \fBncam.srvid2\fR(5), \fBncam.tiers\fR(5), \fBncam.user\fR(5), \fBncam.whitelist\fR(5)
