.TH ncam.cert 5
.SH NAME
\fBncam.cert\fR - Issuer Public Keys (IPK) for NCAm
.SH SYNOPSIS
Issuer Public Keys (IPK)
.SH DESCRIPTIONS
.PP
\fBCAID\fP:\fBreserved\fP:\fBIPK\fP
.RS 3n
mapping between CAID and IPK/sessions keys in hex, currently for Cryptoworks only
.SH EXAMPLES
 0100:00000000:0102030405060708090A0B0C0D0E0F
.RE
.RE
.SH "SEE ALSO"
\fBlist_smargo\fR(1), \fBncam\fR(1), \fBncam.ac\fR(5), \fBncam.cacheex\fR(5), \fBncam.conf\fR(5), \fBncam.dvbapi\fR(5), \fBncam.fakecws\fR(5), \fBncam.guess\fR(5), \fBncam.ird\fR(5), \fBncam.provid\fR(5), \fBncam.ratelimit\fR(5), \fBncam.server\fR(5), \fBncam.services\fR(5), \fBncam.srvid\fR(5), \fBncam.srvid2\fR(5), \fBncam.tiers\fR(5), \fBncam.user\fR(5), \fBncam.whitelist\fR(5)
