.TH ncam.tiers 5
.SH NAME
\fBncam.tiers\fR - TIER configuration file for NCAm
.SH SYNOPSIS
TIER mappings
.SH DESCRIPTIONS
.PP
\fBCAID[,CAID]...\fP:\fBTIER ID\fP|\fBdescription\fP

.RS 3n
mapping between CAID, TIER ID and description of TIER
.RE
.SH ANNONTATIONS
\fIPlease use Unix text file format only.\fR
.SH EXAMPLES
 0001,0002,0003:000a|my TIER 1
 0004:000b|my TIER 2
 0005:000b|my TIER 3
.SH "SEE ALSO"
\fBlist_smargo\fR(1), \fBncam\fR(1), \fBncam.ac\fR(5), \fBncam.cacheex\fR(5), \fBncam.cert\fR(5), \fBncam.conf\fR(5), \fBncam.dvbapi\fR(5), \fBncam.fakecws\fR(5), \fBncam.guess\fR(5), \fBncam.ird\fR(5), \fBncam.provid\fR(5), \fBncam.ratelimit\fR(5), \fBncam.server\fR(5), \fBncam.services\fR(5), \fBncam.srvid\fR(5), \fBncam.srvid2\fR(5), \fBncam.user\fR(5), \fBncam.whitelist\fR(5)
